# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - puzzlepro

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0798c4d1ba7c412099ac64e3885241b8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cf0a3c12135143c08e7a75e3be17373d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0798c4d1ba7c412099ac64e3885241b8 }}/puzzlepro-release:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'puzzlepro'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a276f9bb03e430eb8468dc4fb445f14 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0798c4d1ba7c412099ac64e3885241b8 }}/puzzlepro-release:${{ github.sha }}'